stages:
  - test
  - build

check_python_app:
  stage: test
  image: python:3.10-slim
  script:
    - echo "Checking Python Flask application"
    - pip install -r app/requirements.txt
    - python -m py_compile app/app.py
    - echo "Python app check completed"

build_docker_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Building Docker image"
    - docker --version
    - docker build -t freshmart-grocery-app .
    - echo "Docker image build completed"